name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  publish:
    name: Publish
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          echo "BUILD_DIR=${GITHUB_WORKSPACE}/build" >> $GITHUB_ENV
          echo "PKG_ZIP=${GITHUB_WORKSPACE}/build/pkg.zip" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: package
          path: ${{ env.BUILD_DIR }}

      - name: Upload Thunderstore package
        uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: PapayaMods # the thunderstore 'team' to publish under
          file: ${{ env.PKG_ZIP }}
          token: ${{ secrets.THUNDERSTORE_PROD_API_TOKEN }}
          name: ${{ github.event.repository.name }} # the name of the package
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: lethal-company
          repo: northstar.thunderstore.io
          categories: | # <-- notice this pipe character
            modpacks,
            tools,
            audio,
            suits,
            emotes,
            serverside,
            clientside,
            misc
