name: Validate JSONs

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Set env
        run: |
          echo "PKG_CONTENTS=${GITHUB_WORKSPACE}/build/contents" >> $GITHUB_ENV
          echo "PKG_ZIP=${GITHUB_WORKSPACE}/build/pkg.zip" >> $GITHUB_ENV

      - name: Create unzip destination directory
        run: mkdir -p ${{ env.PKG_CONTENTS }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: package
          path: ${{ env.BUILD_DIR }}

      - name: Unzip modpack
        run: unzip ${{ env.BUILD_PKG }} -d ${{ env.PKG_CONTENTS }}

      - name: Simple JSON validation
        run: jq '.' ${{ env.PKG_CONTENTS }}/manifest.json

      - name: Check presence of icon.png
        run: test -f ${{ env.PKG_CONTENTS }}/icon.png

      - name: Check presence of README.md
        run: test -f ${{ env.PKG_CONTENTS }}/README.md
